name: Build and Push

on:
  workflow_run:
    workflows:
      - "Test and Lint"
    types:
      - completed
    # branches: 
    #   - main
  # # Optional: Allow manual builds
  workflow_dispatch:

jobs:
  build-and-push:
    uses: joel-grant/github-actions/.github/workflows/build-push.yaml@main
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}