name: Build and Push

on:
  push:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-push:
    uses: joel-grant/github-actions/.github/workflows/build-push.yaml@main
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}