name: Deploy Application

on:
  push:
  # Optional: Allow manual deployment
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

permissions:
  contents: write

jobs:
  deploy:
    uses: joel-grant/github-actions/.github/workflows/deploy.yaml@fix-context
    with:
      environment: production
    # Note: Permissions are inherited from the reusable workflow (contents: write)
    secrets:
      kubeconfig: ${{ secrets.KUBECONFIG }}
      kube_context: ${{ secrets.KUBE_CONTEXT }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      secret_name: ${{ secrets.SECRET_NAME }}
      rails_env: ${{ secrets.RAILS_ENV }}
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}
      postgres_port: ${{ secrets.POSTGRES_PORT }}
      postgres_db: ${{ secrets.POSTGRES_DB }}
      postgres_host: ${{ secrets.POSTGRES_HOST }}
      postgres_user: ${{ secrets.POSTGRES_USER }}
      postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
      helm_chart: ${{ secrets.HELM_CHART }}
      k8s_environment: ${{ secrets.K8S_ENVIRONMENT }}
      cloudsmith_username: ${{ secrets.CLOUDSMITH_USERNAME }}
      cloudsmith_api_key: ${{ secrets.CLOUDSMITH_API_KEY }}