name: Release Please

on:
  push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  release:
    uses: joel-grant/github-actions/workflows/release-please.yaml@setup
    secrets:
      MY_RELEASE_PLEASE_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}