name: Release
on:
  push:
    # branches: [ main ]

permissions:
  contents: write        # Required for creating releases
  pull-requests: write   # Required for creating release PRs

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: '.github/release-please-config.json'
          manifest-file: '.github/.release-please-manifest.json'
