name: Test and Lint

on:
  push:

permissions:
  contents: write

jobs:
  test-and-lint:
    uses: joel-grant/github-actions/.github/workflows/test-lint-rails.yaml@main
    with:
      repo_name: "disney-scrapbook"
      ruby_version: 3.4.3
      skip_rubycritic: true
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}